#========================================================================================#
#	Laboratory 316: Reaction-diffusion systems
#
# Author: Niall Palfreyman, March 2025.
#========================================================================================#
[
    Activity(
        """
        Hi! Welcome to Anatta Subject 316: Fields and exploratory processes

        In the module Maxwell, we saw how fields can generate their own dynamics; however, the
        waves we saw there were very predictable. In this lab, we shall look at how agents can
        construct the fields around them in order to generate and maintain patterns thet they
        can use to solve problems. The patterns we shall look at are called Turing patterns, and
        they can be generated by a simple system of chemical reactions and diffusion.
        
        I implemented the module Turing in the usual way: I simply took the module Maxwell - which
        was already close to what I wanted - then stripped out the code I didn't need and modified
        the rest to implement the reaction-diffusion dynamics discovered by the mathematician
        Alan Turing shortly before his death in 1954.

        Run the simulation Turing.demo() now, and simply observe the results without changing any
        settings. Do you see a stable pattern emerging?
        """,
        "The image takes a while to settle down, but eventually you will see white spots forming",
        x -> occursin('y',lowercase(x))
    ),
    Activity(
        """
        Imagine a population of slime-mould organisms on a surface. When slime-mould get hungry,
        they secrete a chemical called Activator (although I have set this secretion rate initially
        to zero). On the surface, Activator catalyses the chemical production of two chemicals: one
        product is Activator itself, and the other is a second chemical called Inhibitor. The
        chemical Inhibitor has this name because it inhibits the chemical production of Activator
        on the surface.

        In addition, these two chemicals also diffuse across the surface and evaporate over time.
        Turing showed (WITHOUT using a computer: he was an amazing man!) that the dynamics of this
        system of chemical reactions between Activator and Inhibitor can generate very interesting
        patterns of the kind you have just observed. What is the name of the method in the Turing
        module that implements chemical reaction, evaporation and diffusion of the two substances?
        """,
        "",
        x -> x=="model_step!"
    ),
    Activity(
        """
        You may be wondering how these Turing dynamics work. Remember that Activator activates the
        production of Inhibitor, whereas Inhibitor INHIBITS the production of Activator. So
        wherever there is strong production of Inhibitor, this will prevent Activator from being
        produced, unless of course Activator levels are so strong that they can maintain themselves
        through autocatalysis. Now notice something interesting: Which chemical has the fastest
        diffusion rate?
        """,
        "I mean the default diffusion rates that I set up - you may need to restart to find them",
        x -> occursin("inhib",lowercase(x))
    ),
    Activity(
        """
        So if we start off at some location with a particularly high Activator concentration, this
        will promote the production of Inhibitor, which then diffuses more quickly than Activator
        away from that location. This forms an inhibiting ring of Inhibitor around the area of high
        Activator concentration. In the Turing module, change the heatmap to :inhibitor to check
        whether this theory is correct: does Inhibitor form spots that are wider than the Activator
        spots?
        """,
        "",
        x -> occursin('y',lowercase(x))
    ),
    Activity(
        """
        While the simulation is running, press "reset" a few times. What changes in the pattern?
        What stays the same? Why? This is a common property of living systems: they exhibit complex
        behaviour that is unpredictable, yet nevertheless constrained by order.
        """,
        "",
        x -> true
    ),
    Activity(
        """
        The reaction-diffusion mechanisms implemented in Turing also take place on the surface of
        animals' skin to create markings - for example, the spots on a dalmation dog or a leopard
        are produced in exactly the same way as the spots you observe here. The only difference is
        that the secreting agents on the skin of a dalmation are not slime-moulds, but rather cells
        called melanocytes. These cells secrete the chemicals that generate the patterns on the
        skin and hair of many animals.
        
        So if we can produce spots, what about stripes? Explore the four sliders for evaporation and
        diffusion rates of the two chemicals to find out which single parameter you must change if
        you want to produce curly stripes:
        """,
        "Change each slider individually, noting first the value to return it to after experimenting",
        x -> "a_diff_rate"
    ),
    Activity(
        """
        As you see, changing these parameters gives us some control over the pattern-formation
        process. In the biological world, organisms determine these parameters genetically, and so
        influence the patterns that form. Note that the pattern-formation process is NOT controlled
        by the organism - all the organism does is modify a parameter that influences this process.
        Rather, the pattern-formation process constitutes an EXPLORATORY mechanism that relieves
        the organism of a lot of work and also a lot of organisational activity.

        In principle, the slime-moulds could influence the diffusion or evaporation rates of the
        chemicals they work with, but here we shall only work with the secretion rate. Raise the
        secretion rate of Activator in steps to find out its influence on the patterns. Does the
        number of slime-moulds occurring inside high concentrations of Activator increase or
        decrease?
        """,
        "",
        x -> occursin("incr",lowercase(x))
    ),
    Activity(
        """
        So we see that the slime-mould organisms can influence the position of the spots or stripes
        that are being formed. They can also stabilise these shapes. As a final exercise in this
        lab, implement tumbling in the slime-moulds:

        Refer to the module PSO to find the tumbling code that the Particles used there to search
        for minima. Copy that code into Turing.agent_step!() and include a slider for the model
        attribute :speed. Now program that method so that if slime-moulds detect a decreasing
        concentration of Activator, they wiggle before moving forward with the model-defined speed.
        Now investigate the effects of the following factors on the patterns generated:
            -	Change the speed slowly upwards from 0.0 to 1.0
            -	Change the secretion rate upwards from 0.0
            -	Experiment with various evaporation and diffusion rates.

        Can you generate a pattern of solid, stable stripes?
        """,
        "",
        x -> true
    ),
    Activity(
        """
        One final point: you may notice that these Turing patterns can take a while to emerge. The
        reason for this is that the two chemicals diffuse at different rates, so the number of
        computational steps required for the chemicals to diffuse across the whole surface is quite
        high. In the biological world, this is not a problem because the pattern-formation process
        takes place not in computational steps, but in continuous dynamical time.

        In lab 316a and module StructuralTuring, I demonstrate how to implement a more efficient
        version of Turing patterns that can be generated much more quickly. This is done by assuming
        that the chemicals switch digitally between "on" and "off" states, rather than taking
        continuous values. This is an inaccurate model of the real world, but is often a reasonable
        approximation, since we are mostly interested in the steady states of the system.

        Don't worry about working through the StructuralTuring code, but remember that the
        implementation is available there in case you want to use it in your own projects. For now,
        proceed on to lab 317.
        """
    ),
]