#========================================================================================#
#	Laboratory 307: How systems choose.
#
# Author: Niall Palfreyman, March 2025.
#========================================================================================#
[
    Activity(
        """
        Hi! Welcome to Anatta Subject 307: Biological choice and differential adhesion.
        
        One of the most exciting aspects of modern biology is the interaction between genetic
        structures and developmental organisation. Stuart Newman and Gerd Müller's Differential
        Adhesion Hypothesis (DAH) is a theory that explains how the physical organisation of an
        organism arises out of the genetic 'stickiness' structure of proteins on the surface of
        each of its cells.
        
        In this laboratory, we explore the concept of 'choice' in biological systems. We will see
        how random decisions made by individual agents can collectively generate complex, self-
        organising choices at the level of the whole system. We first look at the Moran Process: a
        simple stochastic process that demonstrates how agent-based systems amplify the decisions
        of their structural components into a system-wide choice.
        """,
        "",
        x -> true
    ),
    Activity(
        """
        Neutral Drift describes the tendency of genetic structures to mutate randomly, even in
        conditions where the environment exerts no strong selection pressure on them. Neutral
        drift is a crucial factor in the evolutionary process, because it enables genetic
        structures to explore a wide variety of possibilities, even when the environment does not
        favour any particular structure. Neutral drift occurs at a constant rate, and enables us to
        measure the generational distance between the clades of two species, or between two
        populations of the same species.

        Suppose some tribe happens to move to an iron-rich environment which allows them to grow
        taller, giving them the selective advantage of being able to reach higher-hanging fruit.
        Of course, if the tribe moves away to an iron-poor environment, individuals will no longer
        have this advantage. However, so long as they live in the iron-rich environment, neutral
        drift will continue, and competition between individuals will favour those individuals that
        are RELIABLY taller - even if they eat less iron than their neighbours. Consequently, over
        generations, other phenotypic traits will be selected that maintain tallness even when
        individuals absorb less iron from their environment. This is a major controversy in
        evolutionary theory today: Are species and traits ...
            - generated by genetic mutation and then selected by the environment (Darwinism), or
            - generated by the environment and then fixed through genetic drift (neo-Darwinism)?
        """,
        "",
        x -> true
    ),
    Activity(
        """
        Neutral drift of genetic structure therefore plays a hugely important role in evolution. If
        evolutionary change is a ratchet that moves towards increased fitness, neutral drift is the
        pawl that prevents this ratchet from going back to previous, lower-fitness states. Neutral
        drift is the ability of evolutionary systems to cement random variations into a CHOICE.

        Run the module NeutralDrift 5 or 6 times and observe its dynamics. What you observe is a
        Moran Process: each agent possesses either a blue or a green attribute, then at each step,
        the agent replaces this attribute by that of a random neighbour. This attribute may be a
        portion of DNA, a behaviour or a social trait. By exchanging these individual attributes,
        agents build an irreversible collective choice. If we think of green agents as altruists and
        blue agents as non-altruists, we can interpret the Moran process in three different ways:
            -	EVOLUTIONARILY, agents have a random genetic tendency to act altruistically: In
                each generation, agents die and are replaced by a random nearby individual. So
                they tend to be replaced by the most frequent tendency in their neighbourhood.
            -	DEVELOPMENTALLY, altruism is built physiologically: Cells within an organism have a
                random tendency to support altruistic behaviours of the organism. In the process of
                development, cells communicate and modify each others' developmental state. They
                collectively adopt the most common developmental fate in their neighbourhood.
            -	SOCIALLY, altruism is culturally determined: Agents have a random cultural tendency
                to act altruistically. In each generation, agents adopt opinions and behaviours
                from their nearby neighbours. Over time, they therefore tend to adopt the most
                common behaviour in their social neighbourhood.

        Run NeutralDrift again and estimate how often the population chooses in favour of altruism.
        """,
        "Think: Is there any reason to prefer altruism over non-altruism in this model?",
        x -> occursin("half",lowercase(x)) || occursin("50",x) || occursin("0.5",x) || occursin("0,5",x)
    ),
    Activity(
        """
        Notice that this choice is NOT deterministic - it can go either way, and the system can
        take quite a while to make the choice.

        Now run NeutralDrift again, but this time raise the cost of altruism. How much cost do you
        need in order to make the population choose consistently against altruistic behaviour?
        """,
        "",
        x -> (3e-5 ≤ x ≤ 5e-5)
    ),
    Activity(
        """
        As you can see, this Moran choosing process is very unstable! Even an altruism cost of
        just 0.00003 is sufficient to force the choice. Nevertheless, this choosing process has all
        the components of biological choice: it is made by the entire system (not just individual
        components), it is not deterministic, but it is also not pure chance. The choice emerges
        from the actions of the entire system.

        You may remember that we have seen something very like the Moran model before: it is
        similar to the Schelling model in the social sciences, which demonstrates how communities
        organise themselves into tribes or ghettos that collectively choose to adopt a particular
        culture, belief or technology. In this interpretation, altruism is an opinion that either
        spreads through a society or else dies out.
        """,
        "",
        x -> true
    ),
    Activity(
        """
        The Moran model is also similar to the Ising model in statistical mechanics, which
        demonstrates how magnetic materials collectively choose to align their magnetic fields in
        the same direction. In the Ising model, the agents do not interact directly with each other,
        but instead interact with a diffusing and evaporating field B. Green, north-pointing agents
        secrete the signalling factor B, whereas blue south-pointers do not. In each step of the
        Ising model, agents switch their magnetic state between north and south by drawing a random
        value within the range [0,1). If this value is LESS than the local concentration of B, the
        agent sets its north state to TRUE. If the random value is NOT less than the local B
        concentration, the agent switches its north state to FALSE.

        Copy and re-implement the Moran model as an Ising model. You will find that its behaviour
        depends critically upon how fast and far the signalling factor B diffuses outwards from its
        source, so create sliders for the secretion, diffusion and evaporation rates of B. Run the
        model and observe the behaviour of the agents. Notice in particular how the system's global
        choice depends upon these parameters.

        What term describes the mathematical role of the field B play in the switching behaviour of
        Ising agents?
        """,
        "Remember that you are comparing a random number to the local B-field",
        x -> occursin("probab",lowercase(x))
    ),
    Activity(
        """
        Another example of a systemic chooosing process is Newman and Müller's Differential
        Adhesion Hypothesis (DAH), according to which Morphogenesis (i.e., the developmental
        process by which organisms construct themselves) is a choice made by the entire organism.
        This construction process is implemented by proteins called 'cadherins' that stick to each
        other with varying degrees of 'stickiness' on the outer surface of the organism's cells. As
        the cells rattle around due to thermal motion, differential adhesion between cadherins causes
        the cells to organise themselves into the spatial forms that make up the organism's body.

        Run the module DAH and observe the behaviour of the cells. As you see, these cells organise
        themselves according to their 'stickiness' to each other. Experiment now with the various
        slider parameters to discover their effect on the resulting cell patterns. Which change in
        the adhesion_range causes the cells to dissolve: increasing or decreasing it?
        """,
        "",
        x -> occursin("decr",lowercase(x))
    ),
    Activity(
        """
        Reduce adhesion_range to its minimum value, then increase the gravity strength to 0.1. This
        causes the cells to 'fall' towards the centre of the world to form bands of cells. This
        demonstrates how the choice of the cells to organise themselves depends not only on their
        stickiness, but also on the external forces that act upon them. Now increase the number of
        adherin classes and try to find values that construct a stable layered structure of cells.
        """,
        "",
        x -> true
    ),
    Activity(
        """
        To be honest, I think my implementation of the stickiness() method is pretty rubbish. Can
        you do better? Find a way of combining the adherin classes (1:8) that organises the cells
        more cleanly into layers.
        """,
        "",
        x -> true
    ),
]